// Code generated by protoc-gen-go-iam-permissions. DO NOT EDIT.
// source: example.proto

package protofieldmask

import (
	"github.com/mark3labs/mcp-go/mcp"
)

var (
	TestToolTool = mcp.Tool{Name: "abc", Description: "", InputSchema: mcp.ToolInputSchema{Type: "", Properties: map[string]interface{}(nil), Required: []string(nil)}, RawInputSchema: json.RawMessage(nil)}
)
