version: '3'

tasks:
  generate:
    cmds:
      - task: generate-pkg-bqschema
      - task: generate-protoconfig
  generate-pkg-bqschema:
    dir: pkg/bqschema
    cmds:
      - buf generate
      - |
        buf build . -o ./proto/gen/filedescriptorset.binpb
  generate-protoconfig:
    dir: protoconfig
    cmds:
      - buf generate

  test:
    deps:
      - install-tparse
    cmds:
      - |
        go list -f '{{`{{.Dir}}`}}/...' -m | xargs go test -json -v ./... | tparse -trimpath 'github.com/birdayz/protobuf-ecosystem/'
  install-tparse:
    vars:
      VERSION: v0.16.0
    cmds:
      - go install github.com/mfridman/tparse@{{.VERSION}}
    status:
      - '[[ $(tparse --version) == "tparse version: {{.VERSION}}" ]]'
