// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: example.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateExampleRequest_SomeEnum int32

const (
	CreateExampleRequest_SOME_ENUM_UNSPECIFIED CreateExampleRequest_SomeEnum = 0
	CreateExampleRequest_SOME_ENUM_FIRST       CreateExampleRequest_SomeEnum = 1
	CreateExampleRequest_SOME_ENUM_SECOND      CreateExampleRequest_SomeEnum = 2
)

// Enum value maps for CreateExampleRequest_SomeEnum.
var (
	CreateExampleRequest_SomeEnum_name = map[int32]string{
		0: "SOME_ENUM_UNSPECIFIED",
		1: "SOME_ENUM_FIRST",
		2: "SOME_ENUM_SECOND",
	}
	CreateExampleRequest_SomeEnum_value = map[string]int32{
		"SOME_ENUM_UNSPECIFIED": 0,
		"SOME_ENUM_FIRST":       1,
		"SOME_ENUM_SECOND":      2,
	}
)

func (x CreateExampleRequest_SomeEnum) Enum() *CreateExampleRequest_SomeEnum {
	p := new(CreateExampleRequest_SomeEnum)
	*p = x
	return p
}

func (x CreateExampleRequest_SomeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateExampleRequest_SomeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (CreateExampleRequest_SomeEnum) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x CreateExampleRequest_SomeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateExampleRequest_SomeEnum.Descriptor instead.
func (CreateExampleRequest_SomeEnum) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0}
}

type CreateExampleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeInt32      int32                         `protobuf:"varint,1,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeInt64      int64                         `protobuf:"varint,2,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeString     string                        `protobuf:"bytes,3,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeEnum       CreateExampleRequest_SomeEnum `protobuf:"varint,4,opt,name=some_enum,json=someEnum,proto3,enum=main.CreateExampleRequest_SomeEnum" json:"some_enum,omitempty"`
	Nested         *CreateExampleRequest_Nested  `protobuf:"bytes,5,opt,name=nested,proto3" json:"nested,omitempty"`
	OptionalString *string                       `protobuf:"bytes,6,opt,name=optional_string,json=optionalString,proto3,oneof" json:"optional_string,omitempty"`
}

func (x *CreateExampleRequest) Reset() {
	*x = CreateExampleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleRequest) ProtoMessage() {}

func (x *CreateExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleRequest.ProtoReflect.Descriptor instead.
func (*CreateExampleRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *CreateExampleRequest) GetSomeInt32() int32 {
	if x != nil {
		return x.SomeInt32
	}
	return 0
}

func (x *CreateExampleRequest) GetSomeInt64() int64 {
	if x != nil {
		return x.SomeInt64
	}
	return 0
}

func (x *CreateExampleRequest) GetSomeString() string {
	if x != nil {
		return x.SomeString
	}
	return ""
}

func (x *CreateExampleRequest) GetSomeEnum() CreateExampleRequest_SomeEnum {
	if x != nil {
		return x.SomeEnum
	}
	return CreateExampleRequest_SOME_ENUM_UNSPECIFIED
}

func (x *CreateExampleRequest) GetNested() *CreateExampleRequest_Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *CreateExampleRequest) GetOptionalString() string {
	if x != nil && x.OptionalString != nil {
		return *x.OptionalString
	}
	return ""
}

type CreateExampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeString string `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
}

func (x *CreateExampleResponse) Reset() {
	*x = CreateExampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleResponse) ProtoMessage() {}

func (x *CreateExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleResponse.ProtoReflect.Descriptor instead.
func (*CreateExampleResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExampleResponse) GetSomeString() string {
	if x != nil {
		return x.SomeString
	}
	return ""
}

type CreateExampleRequest_Nested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeField string                               `protobuf:"bytes,1,opt,name=some_field,json=someField,proto3" json:"some_field,omitempty"`
	Nested2   *CreateExampleRequest_Nested_Nested2 `protobuf:"bytes,2,opt,name=nested2,proto3" json:"nested2,omitempty"`
}

func (x *CreateExampleRequest_Nested) Reset() {
	*x = CreateExampleRequest_Nested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExampleRequest_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleRequest_Nested) ProtoMessage() {}

func (x *CreateExampleRequest_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleRequest_Nested.ProtoReflect.Descriptor instead.
func (*CreateExampleRequest_Nested) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateExampleRequest_Nested) GetSomeField() string {
	if x != nil {
		return x.SomeField
	}
	return ""
}

func (x *CreateExampleRequest_Nested) GetNested2() *CreateExampleRequest_Nested_Nested2 {
	if x != nil {
		return x.Nested2
	}
	return nil
}

type CreateExampleRequest_Nested_Nested2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeNestedField string                                       `protobuf:"bytes,1,opt,name=some_nested_field,json=someNestedField,proto3" json:"some_nested_field,omitempty"`
	Nested3         *CreateExampleRequest_Nested_Nested2_Nested3 `protobuf:"bytes,2,opt,name=nested3,proto3" json:"nested3,omitempty"`
}

func (x *CreateExampleRequest_Nested_Nested2) Reset() {
	*x = CreateExampleRequest_Nested_Nested2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExampleRequest_Nested_Nested2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleRequest_Nested_Nested2) ProtoMessage() {}

func (x *CreateExampleRequest_Nested_Nested2) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleRequest_Nested_Nested2.ProtoReflect.Descriptor instead.
func (*CreateExampleRequest_Nested_Nested2) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateExampleRequest_Nested_Nested2) GetSomeNestedField() string {
	if x != nil {
		return x.SomeNestedField
	}
	return ""
}

func (x *CreateExampleRequest_Nested_Nested2) GetNested3() *CreateExampleRequest_Nested_Nested2_Nested3 {
	if x != nil {
		return x.Nested3
	}
	return nil
}

type CreateExampleRequest_Nested_Nested2_Nested3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SomeNestedInNestedField string  `protobuf:"bytes,1,opt,name=some_nested_in_nested_field,json=someNestedInNestedField,proto3" json:"some_nested_in_nested_field,omitempty"`
	OptionalString          *string `protobuf:"bytes,2,opt,name=optional_string,json=optionalString,proto3,oneof" json:"optional_string,omitempty"`
}

func (x *CreateExampleRequest_Nested_Nested2_Nested3) Reset() {
	*x = CreateExampleRequest_Nested_Nested2_Nested3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateExampleRequest_Nested_Nested2_Nested3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleRequest_Nested_Nested2_Nested3) ProtoMessage() {}

func (x *CreateExampleRequest_Nested_Nested2_Nested3) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleRequest_Nested_Nested2_Nested3.ProtoReflect.Descriptor instead.
func (*CreateExampleRequest_Nested_Nested2_Nested3) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *CreateExampleRequest_Nested_Nested2_Nested3) GetSomeNestedInNestedField() string {
	if x != nil {
		return x.SomeNestedInNestedField
	}
	return ""
}

func (x *CreateExampleRequest_Nested_Nested2_Nested3) GetOptionalString() string {
	if x != nil && x.OptionalString != nil {
		return *x.OptionalString
	}
	return ""
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x86, 0x06, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x40, 0x0a,
	0x09, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x23, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x6d,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x08, 0x73, 0x6f, 0x6d, 0x65, 0x45, 0x6e, 0x75, 0x6d, 0x12,
	0x39, 0x0a, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x52, 0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x0f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x88, 0x01, 0x01, 0x1a, 0xfd, 0x02, 0x0a, 0x06, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x66, 0x69, 0x65, 0x6c,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x46, 0x69, 0x65,
	0x6c, 0x64, 0x12, 0x43, 0x0a, 0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x52, 0x07,
	0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x1a, 0x8e, 0x02, 0x0a, 0x07, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x32, 0x12, 0x2a, 0x0a, 0x11, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x6e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x73, 0x6f, 0x6d, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x4b, 0x0a, 0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x33, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x2e, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x33, 0x52, 0x07, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x33, 0x1a, 0x89, 0x01, 0x0a,
	0x07, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x33, 0x12, 0x3c, 0x0a, 0x1b, 0x73, 0x6f, 0x6d, 0x65,
	0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x5f, 0x6e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x73,
	0x6f, 0x6d, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x4e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2c, 0x0a, 0x0f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x0e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x88, 0x01, 0x01, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x6c, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x50, 0x0a, 0x08, 0x53, 0x6f, 0x6d, 0x65,
	0x45, 0x6e, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x4f, 0x4d, 0x45, 0x5f, 0x45, 0x4e, 0x55,
	0x4d, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x53, 0x4f, 0x4d, 0x45, 0x5f, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x46, 0x49, 0x52,
	0x53, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x4f, 0x4d, 0x45, 0x5f, 0x45, 0x4e, 0x55,
	0x4d, 0x5f, 0x53, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x10, 0x02, 0x42, 0x12, 0x0a, 0x10, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x38,
	0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x6d, 0x65, 0x5f,
	0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f,
	0x6d, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x32, 0x5a, 0x0a, 0x0e, 0x45, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x73, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x42, 0x0c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x69, 0x72,
	0x64, 0x61, 0x79, 0x7a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d,
	0x6d, 0x63, 0x70, 0x2d, 0x67, 0x6f, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0xa2, 0x02, 0x03, 0x4d, 0x58,
	0x58, 0xaa, 0x02, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0xca, 0x02, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0xe2,
	0x02, 0x10, 0x4d, 0x61, 0x69, 0x6e, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x04, 0x4d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_proto_goTypes = []interface{}{
	(CreateExampleRequest_SomeEnum)(0),                  // 0: main.CreateExampleRequest.SomeEnum
	(*CreateExampleRequest)(nil),                        // 1: main.CreateExampleRequest
	(*CreateExampleResponse)(nil),                       // 2: main.CreateExampleResponse
	(*CreateExampleRequest_Nested)(nil),                 // 3: main.CreateExampleRequest.Nested
	(*CreateExampleRequest_Nested_Nested2)(nil),         // 4: main.CreateExampleRequest.Nested.Nested2
	(*CreateExampleRequest_Nested_Nested2_Nested3)(nil), // 5: main.CreateExampleRequest.Nested.Nested2.Nested3
}
var file_example_proto_depIdxs = []int32{
	0, // 0: main.CreateExampleRequest.some_enum:type_name -> main.CreateExampleRequest.SomeEnum
	3, // 1: main.CreateExampleRequest.nested:type_name -> main.CreateExampleRequest.Nested
	4, // 2: main.CreateExampleRequest.Nested.nested2:type_name -> main.CreateExampleRequest.Nested.Nested2
	5, // 3: main.CreateExampleRequest.Nested.Nested2.nested3:type_name -> main.CreateExampleRequest.Nested.Nested2.Nested3
	1, // 4: main.ExampleService.CreateExample:input_type -> main.CreateExampleRequest
	2, // 5: main.ExampleService.CreateExample:output_type -> main.CreateExampleResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExampleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExampleRequest_Nested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExampleRequest_Nested_Nested2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateExampleRequest_Nested_Nested2_Nested3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_example_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_example_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
