// Code generated by protoc-gen-go-iam-permissions. DO NOT EDIT.
// source: example.proto

package main

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	mcpserver "github.com/mark3labs/mcp-go/server"
	"encoding/json"
	"google.golang.org/protobuf/encoding/protojson"
)

var (
	CreateExampleTool = mcp.Tool{Name: "CreateExample", Description: "", InputSchema: mcp.ToolInputSchema{Type: "object", Properties: map[string]interface{}{"nested": map[string]interface{}{"properties": map[string]interface{}{"nested2": map[string]interface{}{"properties": map[string]interface{}{"nested3": map[string]interface{}{"properties": map[string]interface{}{"optional_string": map[string]interface{}{"type": "string"}, "some_nested_in_nested_field": map[string]interface{}{"type": "string"}}, "required": []string{"some_nested_in_nested_field"}, "type": "object"}, "some_nested_field": map[string]interface{}{"type": "string"}}, "required": []string{"some_nested_field", "nested3"}, "type": "object"}, "some_field": map[string]interface{}{"type": "string"}}, "required": []string{"some_field", "nested2"}, "type": "object"}, "optional_string": map[string]interface{}{"type": "string"}, "some_enum": map[string]interface{}{"enum": []string{"SOME_ENUM_UNSPECIFIED", "SOME_ENUM_FIRST", "SOME_ENUM_SECOND"}, "type": "string"}, "some_int32": map[string]interface{}{"type": "number"}, "some_int64": map[string]interface{}{"type": "string"}, "some_string": map[string]interface{}{"type": "string"}}, Required: []string{"some_int32", "some_int64", "some_string", "some_enum", "nested"}}, RawInputSchema: json.RawMessage(nil)}
)

func RegisterExampleServiceMCP(s *mcpserver.MCPServer, srv ExampleServiceServer) {
	s.AddTool(CreateExampleTool, func(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		marshaled, err := json.Marshal(request.Params.Arguments)
		if err != nil {
			return nil, err
		}

		var req CreateExampleRequest
		if err := protojson.Unmarshal(marshaled, &req); err != nil {
			return nil, err
		}

		resp, err := srv.CreateExample(ctx, &req)
		if err != nil {
			return nil, err
		}

		marshaled, err = protojson.Marshal(resp)
		if err != nil {
			return nil, err
		}
		return mcp.NewToolResultText(string(marshaled)), nil
	})
}
